### ISSUE TITLE
Enhancement: highlight status information in table summary

### ISSUE THREAD

**Issue by pascalrip** [cunninghamp/Get-DailyBackupAlerts.ps1#2]
Hi Paul

Added Color highlighting to status in table view, based on your existing code and HTML header:

Add code line to "Variables"
```powershell
$tdOK="<td>OK</td>"
$tdOKgreen="<td class=""pass"">OK</td>"
$tdALERT="<td>Alert</td>"
$tdALERTred="<td class=""fail"">Alert</td>"
```

Add code line to "Summarise databases with **Alert** status"
```powershell
_$alerthtml = $alerthtml -replace $tdALERT, $tdALERTred_
```
Add code line to "Summarise databases with **OK** status"
```powershell
_$okhtml = $okhtml -replace $tdOK, $tdOKgreen_
```
Best regards
/pascal

**Comment by cunninghamp** [comment]
Added to V1.07
