### ISSUE TITLE
Issue on Exchange 2010?

### ISSUE THREAD

**Issue by SturdyErde** [cunninghamp/Get-DailyBackupAlerts.ps1#5]
This fails for me on Exchange Server 2010 / Windows Server 2008 R2 Enterprise (PowerShell 2.0) with the following error 13 times.

Method invocation failed because [System.String] doesn't contain a method named 'ToInt32'.
At C:\Scripts\Get-DailyBackupAlerts.ps1-1.07\Get-DailyBackupAlerts.ps1:424 char:39
+     elseif ($($LatestBackup.Value.ToInt32 <<<< ($null)) -gt $threshold) {
    + CategoryInfo          : InvalidOperation: (ToInt32:String) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Comment by SturdyErde** [comment]
^ I should have mentioned that the 13 errors correspond to our 13 databases (including 1 public folder).

**Comment by cunninghamp** [comment]
Can you please try the development branch to see if it fixes your issue. Go here and click the "clone or download" button to download a Zip of the files.

https://github.com/cunninghamp/Get-DailyBackupAlerts.ps1/tree/development

**Comment by SturdyErde** [comment]
Looks good now! The script completed without errors.

**Comment by cunninghamp** [comment]
Thanks for confirming.
