### ISSUE TITLE
Issue on Exchange 2010 with new 1.08 release

### ISSUE THREAD

**Issue by TCTulloch** [cunninghamp/Get-DailyBackupAlerts.ps1#7]
It seems on version 1.08, incremental backups are not being reported correctly.

08/25/2016 11:10:24 =====================================
08/25/2016 11:10:24  Exchange Database Backup Check
08/25/2016 11:10:24   08/25/2016 11:10:24
08/25/2016 11:10:24 =====================================
08/25/2016 11:10:24 Threshold for this check is 24 hours
08/25/2016 11:10:24 Loading the Exchange Server PowerShell snapin
08/25/2016 11:10:29 Retrieving database list
08/25/2016 11:10:31 7 mailbox databases found
08/25/2016 11:10:31 0 public folder databases found
08/25/2016 11:10:31 No mailbox databases found
08/25/2016 11:10:31 Removing excluded databases from the checks
08/25/2016 11:10:31 MAILDB004 included
08/25/2016 11:10:31 MAILDB003 included
08/25/2016 11:10:31 MAILDB005 included
08/25/2016 11:10:31 MAILDB006 included
08/25/2016 11:10:31 Mailbox Database 0010239067 excluded
08/25/2016 11:10:31 MAILDB001 included
08/25/2016 11:10:31 MAILDB002 included
08/25/2016 11:10:31 Retrieving list of mailboxes for use in mailbox count later
08/25/2016 11:10:33 ---- Checking MAILDB004 ----
08/25/2016 11:10:33 MAILDB004 has no differential backup timestamp
08/25/2016 11:10:33 Last backup of MAILDB004 was Full  hours ago
08/25/2016 11:10:33 ---- Checking MAILDB003 ----
08/25/2016 11:10:33 MAILDB003 has no differential backup timestamp
08/25/2016 11:10:33 Last backup of MAILDB003 was Full  hours ago
08/25/2016 11:10:33 ---- Checking MAILDB005 ----
08/25/2016 11:10:33 MAILDB005 has no differential backup timestamp
08/25/2016 11:10:33 Last backup of MAILDB005 was Full  hours ago
08/25/2016 11:10:33 ---- Checking MAILDB006 ----
08/25/2016 11:10:33 MAILDB006 has no differential backup timestamp
08/25/2016 11:10:33 Last backup of MAILDB006 was Full  hours ago
08/25/2016 11:10:33 ---- Checking MAILDB001 ----
08/25/2016 11:10:33 MAILDB001 has no differential backup timestamp
08/25/2016 11:10:33 Last backup of MAILDB001 was Full  hours ago
08/25/2016 11:10:33 ---- Checking MAILDB002 ----
08/25/2016 11:10:33 MAILDB002 has no differential backup timestamp
08/25/2016 11:10:33 Last backup of MAILDB002 was Full  hours ago
08/25/2016 11:10:33 6 total databases checked
08/25/2016 11:10:33 Alert email will be sent
08/25/2016 11:10:33 Report summary: Alerts 0, OK 6
08/25/2016 11:10:33 Sending email report
08/25/2016 11:10:33 Finished.

**Comment by cunninghamp** [comment]
Are you saying that your database's last backup was an Incremental, and the email report is incorrect?

Or are you saying that the log just doesn't have info about the last incremental backup timestamp. That is something that doesn't impact the accuracy of the report, but I can update the script to log more information. It would be useful for the log to record all the timestamps actually.

**Comment by TCTulloch** [comment]
The databases last backups were incremental, but the email report is incorrect as the log shows it as full.

**Comment by cunninghamp** [comment]
I found an issue with the script and Exchange 2010 servers. Can you please try the latest development version and let me know if it fixes the issue.

https://github.com/cunninghamp/Get-DailyBackupAlerts.ps1/archive/development.zip

**Comment by TCTulloch** [comment]
It works! The only issue is that the html report shows the backup timestamp in UTC as oppose to local time.


08/30/2016 11:43:50 =====================================
08/30/2016 11:43:50  Exchange Database Backup Check
08/30/2016 11:43:50   08/30/2016 11:43:50
08/30/2016 11:43:50 =====================================
08/30/2016 11:43:50 Threshold for this check is 24 hours
08/30/2016 11:43:50 Loading the Exchange Server PowerShell snapin
08/30/2016 11:44:02 Retrieving database list
08/30/2016 11:44:03 7 mailbox databases found
08/30/2016 11:44:03 0 public folder databases found
08/30/2016 11:44:03 No mailbox databases found
08/30/2016 11:44:03 Removing excluded databases from the checks
08/30/2016 11:44:03 MAILDB004 included
08/30/2016 11:44:03 MAILDB003 included
08/30/2016 11:44:03 MAILDB005 included
08/30/2016 11:44:03 MAILDB006 included
08/30/2016 11:44:03 Mailbox Database 0010239067 excluded
08/30/2016 11:44:03 MAILDB001 included
08/30/2016 11:44:03 MAILDB002 included
08/30/2016 11:44:03 Retrieving list of mailboxes for use in mailbox count later
08/30/2016 11:44:05 ---- Checking MAILDB004 ----
08/30/2016 11:44:05 MAILDB004 last incremental was 08/29/2016 19:01:26 (UTC: 08/29/2016 23:01:26)
08/30/2016 11:44:05 MAILDB004 has no differential backup timestamp
08/30/2016 11:44:05 MAILDB004 last full was 08/28/2016 19:30:54 (UTC: 08/28/2016 23:30:54)
08/30/2016 11:44:05 Last backup of MAILDB004 was Incremental 17 hours ago
08/30/2016 11:44:05 ---- Checking MAILDB003 ----
08/30/2016 11:44:05 MAILDB003 last incremental was 08/29/2016 19:01:26 (UTC: 08/29/2016 23:01:26)
08/30/2016 11:44:05 MAILDB003 has no differential backup timestamp
08/30/2016 11:44:05 MAILDB003 last full was 08/28/2016 19:30:50 (UTC: 08/28/2016 23:30:50)
08/30/2016 11:44:05 Last backup of MAILDB003 was Incremental 17 hours ago
08/30/2016 11:44:05 ---- Checking MAILDB005 ----
08/30/2016 11:44:05 MAILDB005 last incremental was 08/29/2016 19:01:10 (UTC: 08/29/2016 23:01:10)
08/30/2016 11:44:05 MAILDB005 has no differential backup timestamp
08/30/2016 11:44:05 MAILDB005 last full was 08/28/2016 19:31:09 (UTC: 08/28/2016 23:31:09)
08/30/2016 11:44:05 Last backup of MAILDB005 was Incremental 17 hours ago
08/30/2016 11:44:05 ---- Checking MAILDB006 ----
08/30/2016 11:44:05 MAILDB006 last incremental was 08/29/2016 19:01:17 (UTC: 08/29/2016 23:01:17)
08/30/2016 11:44:05 MAILDB006 has no differential backup timestamp
08/30/2016 11:44:05 MAILDB006 last full was 08/28/2016 19:31:08 (UTC: 08/28/2016 23:31:08)
08/30/2016 11:44:05 Last backup of MAILDB006 was Incremental 17 hours ago
08/30/2016 11:44:05 ---- Checking MAILDB001 ----
08/30/2016 11:44:05 MAILDB001 last incremental was 08/29/2016 19:01:27 (UTC: 08/29/2016 23:01:27)
08/30/2016 11:44:05 MAILDB001 has no differential backup timestamp
08/30/2016 11:44:05 MAILDB001 last full was 08/28/2016 19:31:09 (UTC: 08/28/2016 23:31:09)
08/30/2016 11:44:05 Last backup of MAILDB001 was Incremental 17 hours ago
08/30/2016 11:44:05 ---- Checking MAILDB002 ----
08/30/2016 11:44:05 MAILDB002 last incremental was 08/29/2016 19:01:27 (UTC: 08/29/2016 23:01:27)
08/30/2016 11:44:05 MAILDB002 has no differential backup timestamp
08/30/2016 11:44:05 MAILDB002 last full was 08/28/2016 19:30:54 (UTC: 08/28/2016 23:30:54)
08/30/2016 11:44:05 Last backup of MAILDB002 was Incremental 17 hours ago
08/30/2016 11:44:05 6 total databases checked
08/30/2016 11:44:05 Alert email will be sent
08/30/2016 11:44:05 Report summary: Alerts 0, OK 6
08/30/2016 11:44:05 Sending email report

**Comment by cunninghamp** [comment]
Thanks.

The UTC timestamp in the report is deliberate for now. I'm watching feedback to see how well it is received. Some people want it that way, some probably don't.

**Comment by TCTulloch** [comment]
Awesome.
